FORMAT: 1A

# Courses

There are courses here.

## Courses Collection [/courses]

### Show All Courses [GET]

+ Response 200 (application/json)
    
        [
            {
                "count": 1,
                "next": null,
                "previous": null,
                "results":
                [
                    {
                        "name": "Funny English",
                        "description": "We learn english!",
                        "category": 1,
                        "logo": "funnyeng.png",
                        "branches": [
                            {
                                "latitude": "-321313",
                                "longitude": "+65",
                                "address": "3mdr. 67h."
                            }
                        ],
                        "contacts": [
                            {
                                "type": "FACEBOOK",
                                "value": "funnyenglishfb"
                            },
                            {
                                "type": "PHONE",
                                "value": "88005553555"
                            }
                            ]
                    }               
                ]
            }
        ]

### Create a New Course [POST]

+ Request (application/json)
    
        [
            {
                "name": "This field is required.",
                "description": "This field is required.",
                "category": "This field is required.",
                "logo": "This field is required.",
                "branches": [
                    "This field is required."
                ],
                "contacts": [
                    "This field is required."
                ]
            }
        ]

+ Response 201 (application/json)

    + Headers

            Location: /courses/1

    + Body

                [
                    {
                        "name": "Funny English",
                        "description": "We learn english!",
                        "category": 1,
                        "logo": "funnyeng.png",
                        "branches": [
                            {
                                "latitude": "-321313",
                                "longitude": "+65",
                                "address": "3mdr. 67h."
                            }
                        ],
                        "contacts": [
                            {
                                "type": "FACEBOOK",
                                "value": "funnyenglishfb"
                            },
                            {
                                "type": "PHONE",
                                "value": "88005553555"
                            }
                            ]
                    }               
                ]

## Course [/courses/{course_id}]

### View a Course Detail [GET]

+ Response 200 (application/json)
        
                [
                    {
                        "name": "Funny English",
                        "description": "We learn english!",
                        "category": 1,
                        "logo": "funnyeng.png",
                        "branches": [
                            {
                                "latitude": "-321313",
                                "longitude": "+65",
                                "address": "3mdr. 67h."
                            }
                        ],
                        "contacts": [
                            {
                                "type": "FACEBOOK",
                                "value": "funnyenglishfb"
                            },
                            {
                                "type": "PHONE",
                                "value": "88005553555"
                            }
                            ]
                    }               
                ]
    
### Delete the specific Course [DELETE]

+ Response 204